platform :ios, '12.0'

target 'GitHubTrends' do
    use_frameworks!
    pod 'Alamofire', '~> 4.8'
    pod 'SwiftyJSON', '~> 4.3'
    pod 'MarkdownView'
    pod 'AlamofireImage', '~> 3.5'
    pod 'KRProgressHUD', '~> 3.4.0', :inhibit_warnings => true
end
